# Generated by Django 5.2 on 2025-04-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='dayparting',
            field=models.JSONField(default=list),
        ),
    ]
